name: TESTTHING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testcontainerexec:
    runs-on: ubuntu-latest
    steps:
      - name: Run a container command
        run: docker run anchore/engine-cli anchore-cli --u myuser --p mypw --url http://127.0.0.1:8228/v1 system status
