name: TESTTHING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Run env
        run: env
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.7'
      - name: Run go version
        run: go	version
      - name: Run ls
        run: ls -al
      - name: Run go build
        run: go install
      - name: Run tool
        run: syft version
      - name: Generate Source SBOM
        run: echo 'anchorectl sbom -o json create . > ./sbom.json'
      - name: Import Source SBOM
        run: |
          echo anchorectl source import --sbomFile ./sbom.json --repoHost ${GITHUB_SERVER_URL} --repoName ${GITHUB_REPOSITORY} --revision ${GITHUB_SHA}
          echo 'ANCHORE_SOURCE_SBOM_ID=`cat sbom.json | jq .source.target.manifestDigest`'
          export ANCHORE_SOURCE_SBOM_ID=sha256:1234eeee
      - name: Build a Container
        run: docker build -t localimage:latest .
      - name: Generate and Import Image SBOM
        run: |
          echo 'anchorectl -o json sbom upload localimage:latest > sbom.json'
          echo 'ANCHORE_IMAGE_SBOM_ID=`cat sbom.json | jq .source.target.manifestDigest`'
          export ANCHORE_IMAGE_SBOM_ID=sha256:1234ffff
      - name: Get Anchore Application ID
        run: |
          echo 'ANCHORE_APP_ID=`anchorectl -o json application list |jq ".\"data\"[] | select(.name==\"${GITHUB_REPOSITORY}\").application_id"`'
          export ANCHORE_APP_ID=1234
      - name: Get Anchore Application Version
        run: |
          export ANCHORE_APP_VERSION_NAME=`git describe --tags ${GITHUB_SHA}`
          echo 'ANCHORE_APP_VERSION_ID=`anchorectl -o json application version list ${ANCHORE_APP_ID} | jq '.data[] | select(.version_name=="${ANCHORE_APP_VERSION_NAME}").application_version_id'	
          export ANCHORE_APP_VERSION_ID=4567
      - name: Add new source sbom to Anchore application/version
        run: echo 'anchorectl application version artifact add ${ANCHORE_APP_ID} ${ANCHORE_APP_VERSION_ID} source --uuid ${ANCHORE_SOURCE_SBOM_ID}'
      - name: Add new image sbom to Anchore application/version
        run: echo 'anchorectl application version artifact add ${ANCHORE_APP_ID} ${ANCHORE_APP_VERSION_ID} image --image-digest ${ANCHORE_IMAGE_SBOM_ID}'	