name: TESTTHING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testenv:
    runs-on: ubuntu-latest
    steps:
      - name: Run env
        run: env
      - name: Run go version
        run: go	version
      - name: Run ls
        run: ls -al
      - name: Run go build
        run: go install
