name: TESTTHING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Run env
        run: env
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.7'
      - name: Run go version
        run: go	version
      - name: Run ls
        run: ls -al
      - name: Run go build
        run: go install
      - name: Run tool
        run: syft version
      - name: Generate Source SBOM
        run: echo 'anchorectl sbom -o json create . > ./sbom.json'
      - name: Import Source SBOM
        run: echo anchorectl source import --sbomFile ./sbom.json --repoHost ${GITHUB_SERVER_URL} --repoName ${GITHUB_REPOSITORY} --revision ${GITHUB_SHA}
